config/routes.rb
Rails.application.routes.draw do
  get 'categories/index'
  get 'categories/show'
  # devise_for :admins
  # devise_for :users
  devise_for :admins, controllers: {
    sessions:      'admins/sessions',
    passwords:     'admins/passwords',
    registrations: 'admins/registrations'
  }
  devise_for :customers, controllers: {
    sessions:      'customers/sessions',
    passwords:     'customers/passwords',
    registrations: 'customers/registrations'
  }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root to: 'homes#top'

    get 'orders/confirm' => 'orders#confirm'
    get 'orders/thanks' => 'orders#thanks'

  namespace :admin do
    get 'top' => 'homes#top'
    resources :order_products, only: [:update]
    resources :orders, only: [:index, :show, :update]
    resources :customers, only: [:index, :show, :edit, :update] do
      get 'orders' => 'orders#customer_index'
    end
    resources :categories, only: [:index, :create, :edit, :update]
    resources :products, only: [:index, :new, :create, :show, :edit, :update]
  end

  resources :addresses,only: [:index, :create, :destroy, :edit, :update]
  get 'customer' => 'customers#show'
  get 'customers/withdraw' => 'customers#withdraw'
  put 'customers/hide' => 'customers#hide'
  get 'customers/edit_info' => 'customers#edit_info'
  patch 'customers/update' =>'customers#update'
  put 'customers/update' =>'customers#update'
  resources :orders, only: [:new, :create, :index, :show]
  resources :cart_items, only: [:index, :create, :destroy, :update]
  delete 'cart_items_all' => 'cart_items#destroy_all'
  resources :products, only: [:index, :show]
  resources :categories, only: [:index, :show] do
    get 'products' => 'categories#index'
  end

end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :products, through: :cart_items, dependent: :destroy
  has_many :addresses, dependent: :destroy
  has_many :orders, dependent: :destroy
  has_many :cart_items, dependent: :destroy

  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :first_name_kana, presence: true
  validates :last_name_kana, presence: true
  validates :postcode, presence: true
  validates :address, presence: true
  validates :phone_number, presence: true

  def active_for_authentication?
    super && (self.is_deleted == false)
  end
end

app/controllers/admin/customers_controller.rb
class Admin::CustomersController < ApplicationController
  before_action :authenticate_admin!
  def index
    @customers = Customer.page(params[:page]).reverse_order
  end

  def show
    @customer = Customer.find(params[:id])
    
  end

  def edit
    @customer = Customer.find(params[:id])
  end

  def update
    @customer = Customer.find(params[:id])
    if @customer.update(customer_params)
      flash[:notice] = "会員情報を編集しました。"
      redirect_to admin_customer_path(@customer)
    else
      render :edit
    end
  end

  protected
  def customer_params
    params.require(:customer).permit(:first_name, :last_name, :first_name_kana, :last_name_kana, :email, :postcode, :address, :phone_number, :is_deleted)
  end
end

app/controllers/customers/confirmations_controller.rb
# frozen_string_literal: true

class Customers::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/customers/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Customers::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/customers/passwords_controller.rb
# frozen_string_literal: true

class Customers::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/customers/registrations_controller.rb
# frozen_string_literal: true

class Customers::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/customers/sessions_controller.rb
# frozen_string_literal: true

class Customers::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]
  before_action :reject_customer, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end

  protected
  def reject_customer
    @customer = Customer.find_by(email: params[:customer][:email].downcase)
    if @customer
      if (@customer.valid_password?(params[:customer][:password]) && (@customer.active_for_authentication? == false))
        flash[:error] = "退会済みです。"
        redirect_to new_customer_session_path
      end
    else
      flash[:error] = "必須項目を入力してください。"
    end
  end
end

app/controllers/customers/unlocks_controller.rb
# frozen_string_literal: true

class Customers::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
  before_action :authenticate_customer!
  def show
    @customer = Customer.find(current_customer.id)
  end

  def withdraw
    @customer = Customer.find(current_customer.id)
  end

  def hide
    @customer = Customer.find(current_customer.id)
    @customer.update(is_deleted: true)
    reset_session
    flash[:notice] = "ありがとうございました。またのご利用を心よりお待ちしております。"
    redirect_to root_path
  end

  def edit_info
    @customer = Customer.find(current_customer.id)
  end

  def update
    @customer = Customer.find(current_customer.id)
    if @customer.update(customer_params)
      flash[:notice] = "You have updated customer successfully."
      redirect_to customer_path(@customer)
    else
      render :edit
    end
  end

  protected
  def customer_params
    params.require(:customer).permit(:first_name, :last_name, :first_name_kana, :last_name_kana, :email, :postcode, :address, :phone_number)
  end
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/views/admin/customers/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-9">
      <h1><strong>会員編集画面</strong></h1>
      <%= form_for(@customer, url: admin_customer_path, method: :put) do |f| %>
      <table class="admin-customer-table">
        <tr>
          <td>会員ID</td>
          <td><%= @customer.id %></td>
        </tr>
        <tr>
          <td>氏名</td>
          <td width="150">
            <%= f.text_field :last_name, autofocus: true, class:"customer-signup_form, form-control" %>
          </td>
          <td>
            <%= f.text_field :first_name, autofocus: true, class:"customer-signup_form, form-control" %>
          </td>
        </tr>

        <tr>
          <td>フリガナ</td>
          <td class="customer-name_form">
            <%= f.text_field :last_name_kana, autofocus: true, class:"customer-signup_form, form-control" %>
          </td>
          <td>
            <%= f.text_field :first_name_kana, autofocus: true, class:"customer-signup_form, form-control" %>
          </td>
        </tr>

        <tr>
          <td>郵便番号(ハイフンなし)</td>
          <td>
            <%= f.text_field :postcode, autofocus: true, class:"customer-signup_form, form-control" %>
          </td>
        </tr>

        <tr>
          <td>住所</td>
          <td colspan="4">
            <%= f.text_field :address, autofocus: true, class:"form-control" %>
          </td>
        </div>

        <tr>
          <td>電話番号(ハイフンなし)</td>
          <td>
            <%= f.text_field :phone_number, autofocus: true, class:"customer-signup_form, form-control" %>
          </td>
        </tr>

        <tr>
          <td>メールアドレス</td>
          <td>
            <%= f.email_field :email, autofocus: true, class:"customer-signup_form, form-control" %>
          </td>
        </tr>

        <tr>
          <td>会員ステータス</td>
          <td><%= f.radio_button :is_deleted, false %>有効 <%= f.radio_button :is_deleted, true %> 退会済み</td>
        </tr>

      </table>
      <div>
        <%= f.submit "変更を保存する",class:"btn admin-customer-update active" %>
      </div>
      <% end %>
    </div>
  </div>
</div>

app/views/admin/customers/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-12">
      <h1><strong>会員一覧画面</strong></h1>
      <table class="table">
        <tr bgcolor="#eee">
          <th>会員ID</th>
          <th>氏名</th>
          <th>メールアドレス</th>
          <th>ステータス</th>
        </tr>
         <% @customers.each do |customer| %>
         <tr>
           <td><%= customer.id %></td>
           <td>
            <%= link_to admin_customer_path(customer) do %>
            <%= customer.last_name %><%= customer.first_name %>
            <% end %>
           </td>
           <td><%= customer.email %></td>
           <% if customer.is_deleted == false %>
           <td>有効</td>
           <% else %>
           <td>退会済み</td>
           <% end %>
         </tr>
         <% end %>
         <%= paginate @customers, class: "paginate" %>
      </table>
    </div>
  </div>
</div>

app/views/admin/customers/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-9">
      <h1><strong>会員詳細画面</strong></h1>
      <table class="admin-customer-table">
        <tr>
          <td width="120">顧客ID</td>
          <td><%= @customer.id %>
            <% if @customer.is_deleted == false %>
              <span class="customer-definition">有効会員</span>
            <% else %>
              <span class="customer-definition">無効会員</span>
            <%end%>
          </td>
        </tr>
        <tr>
          <td>氏名</td>
          <td><%= @customer.last_name %><%= @customer.first_name %></td>
        </tr>
        <tr>
          <td>フリガナ</td>
          <td><%= @customer.last_name_kana %><%= @customer.first_name_kana %></td>
        </tr>
        <tr>
          <td>郵便番号</td>
          <td><%= @customer.postcode %></td>
        </tr>
        <tr>
          <td>住所</td>
          <td><%= @customer.address %></td>
        </tr>
        <tr>
          <td>電話番号</td>
          <td><%= @customer.phone_number %></td>
        </tr>
        <tr>
          <td>メールアドレス</td>
          <td><%= @customer.email %></td>
        </tr>
        <tr>
          <td><%= link_to "編集する", edit_admin_customer_path(@customer), class:"btn btn-primary" %></td>
          <td><%= link_to "注文履歴一覧を見る", admin_customer_orders_path(@customer), class:"btn btn-primary" %></td>
        </tr>
      </table>
    </div>
  </div>
</div>