config/routes.rb
Rails.application.routes.draw do
  get 'categories/index'
  get 'categories/show'
  # devise_for :admins
  # devise_for :users
  devise_for :admins, controllers: {
    sessions:      'admins/sessions',
    passwords:     'admins/passwords',
    registrations: 'admins/registrations'
  }
  devise_for :customers, controllers: {
    sessions:      'customers/sessions',
    passwords:     'customers/passwords',
    registrations: 'customers/registrations'
  }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root to: 'homes#top'

    get 'orders/confirm' => 'orders#confirm'
    get 'orders/thanks' => 'orders#thanks'

  namespace :admin do
    get 'top' => 'homes#top'
    resources :order_products, only: [:update]
    resources :orders, only: [:index, :show, :update]
    resources :customers, only: [:index, :show, :edit, :update] do
      get 'orders' => 'orders#customer_index'
    end
    resources :categories, only: [:index, :create, :edit, :update]
    resources :products, only: [:index, :new, :create, :show, :edit, :update]
  end

  resources :addresses,only: [:index, :create, :destroy, :edit, :update]
  get 'customer' => 'customers#show'
  get 'customers/withdraw' => 'customers#withdraw'
  put 'customers/hide' => 'customers#hide'
  get 'customers/edit_info' => 'customers#edit_info'
  patch 'customers/update' =>'customers#update'
  put 'customers/update' =>'customers#update'
  resources :orders, only: [:new, :create, :index, :show]
  resources :cart_items, only: [:index, :create, :destroy, :update]
  delete 'cart_items_all' => 'cart_items#destroy_all'
  resources :products, only: [:index, :show]
  resources :categories, only: [:index, :show] do
    get 'products' => 'categories#index'
  end

end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :customer
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :customer
  belongs_to :product
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :products, dependent: :destroy
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :products, through: :cart_items, dependent: :destroy
  has_many :addresses, dependent: :destroy
  has_many :orders, dependent: :destroy
  has_many :cart_items, dependent: :destroy

  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :first_name_kana, presence: true
  validates :last_name_kana, presence: true
  validates :postcode, presence: true
  validates :address, presence: true
  validates :phone_number, presence: true

  def active_for_authentication?
    super && (self.is_deleted == false)
  end
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :customer
  has_many :order_products, dependent: :destroy
  enum status:{waitmoney:0, moneycheck:1, making:2, sentready:3, finishsenting:4}

end

app/models/order_product.rb
class OrderProduct < ApplicationRecord
  belongs_to :order
  enum status:{impossible:0, waitmake:1, making:2, finishmaking:3}
end

app/models/product.rb
class Product < ApplicationRecord
  has_many :customers,  through: :cart_items
  belongs_to :category

  attachment :image

	validates :image, presence: true
	validates :name, presence: true
	validates :detail, presence: true
	validates :category_id, presence: true
	validates :no_tax_price, presence: true
	validates :is_available, presence: true

end

app/models/user.rb
class User < ApplicationRecord
end

app/controllers/admin/categories_controller.rb
class Admin::CategoriesController < ApplicationController
  before_action :authenticate_admin!
  def index
  	@categories = Category.all
  	@category = Category.new
  end

  def create
  	@category = Category.new(category_params)
  	if @category.save
  		flash[:success] = "Category was successfully added."
  		redirect_to admin_categories_path
  	end
  end

  def edit
  	@category = Category.find(params[:id])
  end

  def update
  	@category = Category.find(params[:id])
  	if @category.update(category_params)
  		redirect_to admin_categories_path, notice: "Category was successfully updated."
  	else
  		render "edit"
  	end
  end

  private

  def category_params
  	params.require(:category).permit(:name, :is_enabled)
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def index
  	# この記述でジャンルステータスが有効のカテゴリーのみ表示
	 	@categories = Category.where(is_enabled: true)
  	if params[:category_id]
		 	@category = Category.find(params[:category_id])
			@products = Product.where(category_id: params[:category_id]).page(params[:page])
	  end
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
	def top
  	# この記述でジャンルステータスが有効のカテゴリーのみ表示
	 	@categories = Category.where(is_enabled: true)
		@products = Product.offset(rand(Product.count)).first(4)
	end
end



# home.top.html.erbの記述。
# Home.top

# <% @products.each do|product| %>
# 		<%= product.image %>
# 		<%= product.name %>
# 		<%= product.no_tax_price %>
# 	<% end %>

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :authenticate_customer!
  def new
    @order = Order.new
  end

  def confirm
    @cart_items = current_customer.cart_items
    @orders = current_customer
    @order = Order.new
  end

  def create
    order = Order.new(order_params)
    order.customer_id = current_customer.id
    order.save
    current_customer.cart_items.each do |f|
      op = OrderProduct.new(name: f.product.name , quantity: f.quantity , price: f.quantity * f.product.no_tax_price * 1.1, order_id: order.id , status: 0)
      op.save
      f.destroy
    end
    redirect_to orders_thanks_path
  end

  def thanks
  end

  def index
    @orders = current_customer.orders
  end

  def show
    @order = Order.find(params[:id])
  end

  private

  def order_params
    params.require(:order).permit(:payment_method, :postcode, :address, :name ,:charge)
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
  	# この記述でジャンルステータスが有効のカテゴリーのみ表示
	 	@categories = Category.where(is_enabled: true)

		@products = []
		# .page(params[:page]).all
		@categories.each do |category|
			category.products.each do |product|
				if product.is_available == true
					@products << product
				end
			end
		end
		@products = Kaminari.paginate_array(@products).page(params[:page]).per(8)
  end

  def show
  	# この記述でジャンルステータスが有効のカテゴリーのみ表示
	 	@categories = Category.where(is_enabled: true)
  	@product = Product.find(params[:id])
  	@cart_item = CartItem.new
  end
end

app/helpers/addresses_helper.rb
module AddressesHelper
end

app/helpers/admin/categories_helper.rb
module Admin::CategoriesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cart_items_helper.rb
module CartItemsHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/enum_helper.rb
module EnumHelper
  # クラスオブジェクトとカラム名を引数として呼ばれるコールバック関数です
  def options_for_select_from_enum(klass,column)
    #該当クラスのEnum型リストをハッシュで取得
    enum_list = klass.send(column.to_s.pluralize)
    #Enum型のハッシュリストに対して、nameと日本語化文字列の配列を取得（valueは使わないため_)
    enum_list.map do | name , _value |
      # selectで使うための組み合わせ順は[ 表示値, value値 ]のため以下の通り設定
      [ t("enums.#{klass.to_s.downcase}.#{column}.#{name}") , name ]
    end
  end
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
  def converting_to_jpy(price)
    "#{price.to_s(:delimited, delimiter: ',')}"
  end
end

app/helpers/products_helper.rb
module ProductsHelper
  def converting_to_jpy(price)
    "#{price.to_s(:delimited, delimiter: ',')}"
  end
end

app/views/admin/categories/edit.html.erb
<div class="container">
	<div class="row">
		<h1><strong>ジャンル編集画面</strong></h1>
		<table class="category-form">
			<%= form_with(model: @category, local: true, url: admin_category_path) do |f| %>
				<tr class="category-new">
					<td><%= f.label :ジャンル %></td>
					<td><%= f.text_field :name, class:"form-control" %></td>
					<td><%= f.radio_button :is_enabled, true %> 有効</td>
					<td><%= f.radio_button :is_enabled, false %> 無効</td>
					<td><%= f.submit "変更を保存する", class:"btn category-update active" %></td>
				</tr>
			<% end %>
		</table>
	</div>
</div>

app/views/admin/categories/index.html.erb
<div class="container">
	<div class="row">
		<h1><strong>ジャンル追加・一覧画面</strong></h1>
		<table class="category-form">
			<%= form_with(model: @category, local: true, url: admin_categories_path) do |f| %>
				<tr class="category-new">
					<td><%= f.label :ジャンル %></td>
					<td><%= f.text_field :name, class:"form-control" %></td>
					<td><%= f.radio_button :is_enabled, true %> 有効</td>
					<td><%= f.radio_button :is_enabled, false %> 無効</td>
					<td><%= f.submit "追加", class:"btn category-add active" %></td>
				</tr>
			<% end %>
		</table>

		<table class="table table-bordered" style="width: 30%;">
			<thead bgcolor="#eee">
				<tr>
					<th width="30%">ジャンル</th>
					<th width="30%">状態</th>
					<th width="40%"></th>
				</tr>
			</thead>
			<tbody>
				<% @categories.each do |category| %>
				<tr>
					<td><%= category.name %></td>
					<% if category.is_enabled == true %>
						<td>有効</td>
					<% else %>
						<td>無効</td>
					<% end %>
					<td><%= link_to "編集する", edit_admin_category_path(category.id), class:"btn category-edit" %></td>
				<% end %>
			</tbody>
		</table>
	</div>
</div>

app/views/categories/_link.html.erb
<div class="col-xs-2">
			<div class="categories">
				<h4 class="categories-serch">ジャンル検索</h4>
				<% categories.each do |category| %>
					  <p><%= link_to category.name, category_products_path(category.id) %></p>
				<% end %>
			</div>
		</div>

app/views/categories/index.html.erb
<div class="container">
	<div class="row">
		<%= render 'link', categories: @categories %>

		<div class="col-xs-10">
			<div class="product-top">
					<h1><%= @category.name %>一覧</h1>
					<p>(全<%= @products.count %>件)</p>
			</div>
			<%= render 'products/product_index', products: @products %>
		</div>
	</div>
</div>