config/routes.rb
Rails.application.routes.draw do
  get 'categories/index'
  get 'categories/show'
  # devise_for :admins
  # devise_for :users
  devise_for :admins, controllers: {
    sessions:      'admins/sessions',
    passwords:     'admins/passwords',
    registrations: 'admins/registrations'
  }
  devise_for :customers, controllers: {
    sessions:      'customers/sessions',
    passwords:     'customers/passwords',
    registrations: 'customers/registrations'
  }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root to: 'homes#top'

    get 'orders/confirm' => 'orders#confirm'
    get 'orders/thanks' => 'orders#thanks'

  namespace :admin do
    get 'top' => 'homes#top'
    resources :order_products, only: [:update]
    resources :orders, only: [:index, :show, :update]
    resources :customers, only: [:index, :show, :edit, :update] do
      get 'orders' => 'orders#customer_index'
    end
    resources :categories, only: [:index, :create, :edit, :update]
    resources :products, only: [:index, :new, :create, :show, :edit, :update]
  end

  resources :addresses,only: [:index, :create, :destroy, :edit, :update]
  get 'customer' => 'customers#show'
  get 'customers/withdraw' => 'customers#withdraw'
  put 'customers/hide' => 'customers#hide'
  get 'customers/edit_info' => 'customers#edit_info'
  patch 'customers/update' =>'customers#update'
  put 'customers/update' =>'customers#update'
  resources :orders, only: [:new, :create, :index, :show]
  resources :cart_items, only: [:index, :create, :destroy, :update]
  delete 'cart_items_all' => 'cart_items#destroy_all'
  resources :products, only: [:index, :show]
  resources :categories, only: [:index, :show] do
    get 'products' => 'categories#index'
  end

end

app/models/product.rb
class Product < ApplicationRecord
  has_many :customers,  through: :cart_items
  belongs_to :category

  attachment :image

	validates :image, presence: true
	validates :name, presence: true
	validates :detail, presence: true
	validates :category_id, presence: true
	validates :no_tax_price, presence: true
	validates :is_available, presence: true

end

app/controllers/admin/products_controller.rb
class Admin::ProductsController < ApplicationController
  before_action :authenticate_admin!
  def index
    @products = Product.all
  end

  def new
    @product = Product.new
  end

  def create
    @products = Product.all
    @product = Product.new(product_params)
    if @product.save
      flash[:success] = "Product was successfully added."
      redirect_to admin_products_path
    end
  end

  def show
    @product = Product.find(params[:id])
  end

  def edit
    @product = Product.find(params[:id])
  end

  def update
    @product = Product.find(params[:id])
    if @product.update(product_params)
      redirect_to admin_product_path, notice: "Product was successfully updated."
    else
      render "edit"
    end
  end
  private

  def product_params
    params.require(:product).permit(:image, :name, :detail, :category_id, :no_tax_price, :is_available)
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
  	# この記述でジャンルステータスが有効のカテゴリーのみ表示
	 	@categories = Category.where(is_enabled: true)

		@products = []
		# .page(params[:page]).all
		@categories.each do |category|
			category.products.each do |product|
				if product.is_available == true
					@products << product
				end
			end
		end
		@products = Kaminari.paginate_array(@products).page(params[:page]).per(8)
  end

  def show
  	# この記述でジャンルステータスが有効のカテゴリーのみ表示
	 	@categories = Category.where(is_enabled: true)
  	@product = Product.find(params[:id])
  	@cart_item = CartItem.new
  end
end

app/helpers/admin/products_helper.rb
module Admin::ProductsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
  def converting_to_jpy(price)
    "#{price.to_s(:delimited, delimiter: ',')}"
  end
end

app/views/products/_product_index.html.erb
	<!-- 以下は gem "kaminari" -->
	<% products.each do |product| %>
	<div class="product-block">
		<!-- 下記の記述で商品写真 -->
		<div class="block block-image">
			<%= link_to product_path(product.id) do %>
			<%= attachment_image_tag product, :image, :fill, 210, 130 %>
			<% end %>
		</div>
		<!-- 下記の記述で商品名 -->
		<div class="block-name" style="padding: 10px 0;">
			<%= product.name %>
		</div>
		<!-- 下記の記述で商品価格 -->
		<div class="block-price">
			<% price = (BigDecimal(product.no_tax_price) * BigDecimal("1.1")).ceil %>
			¥<%= converting_to_jpy(price) %>
		</div>
	</div>
	<% end %>
	<div class="page">
		<%= paginate products, class: "paginate" %>
	</div>

app/views/products/index.html.erb
<div class="container">
	<div class="row">
		<%= render 'categories/link', categories: @categories %>

		<div class="col-xs-10">
			<div class="product-top">
					<h1>商品一覧</h1>
					<p>(全<%= @products.count %>件)</p>
			</div>
			<!-- 以下は gem "kaminari" -->
			<%= render 'product_index', products: @products %>
		</div>
	</div>
</div>

app/views/products/show.html.erb
<div class="container">
	<div class="row">
		<div class="col-xs-2">
			<div class="categories">
				<h4 class="categories-serch">ジャンル検索</h4>
				<% @categories.each do |category| %>
					  <p><%= link_to category.name, category_products_path(category.id) %></p>
				<% end %>
			</div>
		</div>
		<!-- ジャンルと商品の詳細の間の空白 -->
		<div class="col-xs-1">
		</div>
		<!-- 商品詳細 -->
		<%= form_with(model: @cart_item, local: true, url: cart_items_path) do |f|  %>
			<div class="col-xs-9">
				<div class="row">
					<div class="col-xs-6">
						<%= attachment_image_tag @product, :image, :fill, 400, 260 %>
					</div>
					<div class="col-xs-6">
						<h1><%= @product.name %></h1>
						<p><%= @product.detail %></p>
						<!-- 小数点以下の切り捨てと、消費税1.1%の掛け算 -->
						<% price = (BigDecimal(@product.no_tax_price) * BigDecimal("1.1")).ceil %>
						<h3>¥ <%= converting_to_jpy(price) %>（税込）</h3>
					</div>
				</div>
				<!-- 注文個数はセレクトボタンで生成 -->
				<div style="margin: 20px; text-align: right;">
				<%= f.select :quantity, options_for_select((1..25).to_a), include_blank: "個数選択", class:"quantity-select" %>
				<!-- カートに入れるボタン -->
				<%= f.hidden_field :product_id, :value => @product.id %>
				<%= f.submit "カートに入れる", class:"btn cart-add active" %>
				</div>
			<% end %>
		</div>
	</div>
</div>